services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/var/www
    networks:
      - laravel-network

  web:
    image: nginx:alpine
    container_name: laravel-nginx
    volumes:
      - .:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8081:80"
    networks:
      - laravel-network

  db:
    image: mysql:5.7
    container_name: laravel-mysql
    restart: always
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - laravel-network
    ports:
      - "3306:3306"

  node:
    image: node:14
    container_name: laravel-node
    working_dir: /var/www
    volumes:
      - .:/var/www
    networks:
      - laravel-network

volumes:
  db_data:

networks:
  laravel-network:
    driver: bridge
